name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: login to docker hub
      env:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}  
      run: docker login -u $username -p $password 
      
    - uses: actions/checkout@v4
    - name: Build the core image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/openas2:latest
    - name: Build the UI image
      run: docker build . --file Dockerfile_WebUI --tag ${{secrets.DOCKER_USERNAME}}/openas2_webui:latest

    - name: Push core to Docker
      run: docker push ${{secrets.DOCKER_USERNAME}}/openas2:latest
    - name: Push core to Docker
      run: docker push ${{secrets.DOCKER_USERNAME}}/openas2_webui:latest

